# Generated by Django 5.0.3 on 2024-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_class', models.IntegerField(choices=[(1, 'airplane'), (2, 'automobile'), (3, 'bird'), (4, 'cat'), (5, 'deer'), (6, 'dog'), (7, 'frog'), (8, 'horse'), (9, 'ship'), (10, 'truck')])),
                ('image_predicted_class', models.IntegerField(choices=[(1, 'airplane'), (2, 'automobile'), (3, 'bird'), (4, 'cat'), (5, 'deer'), (6, 'dog'), (7, 'frog'), (8, 'horse'), (9, 'ship'), (10, 'truck')])),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
