# Generated by Django 5.0.3 on 2024-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_class',
            field=models.IntegerField(choices=[(0, 'airplane'), (1, 'automobile'), (2, 'bird'), (3, 'cat'), (4, 'deer'), (5, 'dog'), (6, 'frog'), (7, 'horse'), (8, 'ship'), (9, 'truck')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_predicted_class',
            field=models.IntegerField(choices=[(0, 'airplane'), (1, 'automobile'), (2, 'bird'), (3, 'cat'), (4, 'deer'), (5, 'dog'), (6, 'frog'), (7, 'horse'), (8, 'ship'), (9, 'truck')]),
        ),
    ]
